import adImage from './flagSvgs/ad.svg';
import aeImage from './flagSvgs/ae.svg';
import afImage from './flagSvgs/af.svg';
import agImage from './flagSvgs/ag.svg';
import aiImage from './flagSvgs/ai.svg';
import alImage from './flagSvgs/al.svg';
import amImage from './flagSvgs/am.svg';
import aoImage from './flagSvgs/ao.svg';
import aqImage from './flagSvgs/aq.svg';
import arImage from './flagSvgs/ar.svg';
import asImage from './flagSvgs/as.svg';
import atImage from './flagSvgs/at.svg';
import auImage from './flagSvgs/au.svg';
import awImage from './flagSvgs/aw.svg';
import axImage from './flagSvgs/ax.svg';
import azImage from './flagSvgs/az.svg';
import baImage from './flagSvgs/ba.svg';
import bbImage from './flagSvgs/bb.svg';
import bdImage from './flagSvgs/bd.svg';
import beImage from './flagSvgs/be.svg';
import bfImage from './flagSvgs/bf.svg';
import bgImage from './flagSvgs/bg.svg';
import bhImage from './flagSvgs/bh.svg';
import biImage from './flagSvgs/bi.svg';
import bjImage from './flagSvgs/bj.svg';
import blImage from './flagSvgs/bl.svg';
import bmImage from './flagSvgs/bm.svg';
import bnImage from './flagSvgs/bn.svg';
import boImage from './flagSvgs/bo.svg';
import bqImage from './flagSvgs/bq.svg';
import brImage from './flagSvgs/br.svg';
import bsImage from './flagSvgs/bs.svg';
import btImage from './flagSvgs/bt.svg';
import bwImage from './flagSvgs/bw.svg';
import byImage from './flagSvgs/by.svg';
import bzImage from './flagSvgs/bz.svg';
import caImage from './flagSvgs/ca.svg';
import ccImage from './flagSvgs/cc.svg';
import cdImage from './flagSvgs/cd.svg';
import cfImage from './flagSvgs/cf.svg';
import cgImage from './flagSvgs/cg.svg';
import chImage from './flagSvgs/ch.svg';
import ciImage from './flagSvgs/ci.svg';
import ckImage from './flagSvgs/ck.svg';
import clImage from './flagSvgs/cl.svg';
import cmImage from './flagSvgs/cm.svg';
import cnImage from './flagSvgs/cn.svg';
import coImage from './flagSvgs/co.svg';
import crImage from './flagSvgs/cr.svg';
import cuImage from './flagSvgs/cu.svg';
import cvImage from './flagSvgs/cv.svg';
import cwImage from './flagSvgs/cw.svg';
import cxImage from './flagSvgs/cx.svg';
import cyImage from './flagSvgs/cy.svg';
import czImage from './flagSvgs/cz.svg';
import deImage from './flagSvgs/de.svg';
import djImage from './flagSvgs/dj.svg';
import dkImage from './flagSvgs/dk.svg';
import dmImage from './flagSvgs/dm.svg';
import doImage from './flagSvgs/do.svg';
import dzImage from './flagSvgs/dz.svg';
import ecImage from './flagSvgs/ec.svg';
import eeImage from './flagSvgs/ee.svg';
import egImage from './flagSvgs/eg.svg';
import ehImage from './flagSvgs/eh.svg';
import erImage from './flagSvgs/er.svg';
import esImage from './flagSvgs/es.svg';
import etImage from './flagSvgs/et.svg';
import fiImage from './flagSvgs/fi.svg';
import fjImage from './flagSvgs/fj.svg';
import fkImage from './flagSvgs/fk.svg';
import fmImage from './flagSvgs/fm.svg';
import foImage from './flagSvgs/fo.svg';
import frImage from './flagSvgs/fr.svg';
import gaImage from './flagSvgs/ga.svg';
import gbImage from './flagSvgs/gb.svg';
import gbengImage from './flagSvgs/gb-eng.svg';
import gbnirImage from './flagSvgs/gb-nir.svg';
import gbsctImage from './flagSvgs/gb-sct.svg';
import gbwlsImage from './flagSvgs/gb-wls.svg';
import gdImage from './flagSvgs/gd.svg';
import geImage from './flagSvgs/ge.svg';
import gfImage from './flagSvgs/gf.svg';
import ggImage from './flagSvgs/gg.svg';
import ghImage from './flagSvgs/gh.svg';
import giImage from './flagSvgs/gi.svg';
import glImage from './flagSvgs/gl.svg';
import gmImage from './flagSvgs/gm.svg';
import gnImage from './flagSvgs/gn.svg';
import gpImage from './flagSvgs/gp.svg';
import gqImage from './flagSvgs/gq.svg';
import grImage from './flagSvgs/gr.svg';
import gsImage from './flagSvgs/gs.svg';
import gtImage from './flagSvgs/gt.svg';
import guImage from './flagSvgs/gu.svg';
import gwImage from './flagSvgs/gw.svg';
import gyImage from './flagSvgs/gy.svg';
import hkImage from './flagSvgs/hk.svg';
import hmImage from './flagSvgs/hm.svg';
import hnImage from './flagSvgs/hn.svg';
import hrImage from './flagSvgs/hr.svg';
import htImage from './flagSvgs/ht.svg';
import huImage from './flagSvgs/hu.svg';
import idImage from './flagSvgs/id.svg';
import ieImage from './flagSvgs/ie.svg';
import ilImage from './flagSvgs/il.svg';
import imImage from './flagSvgs/im.svg';
import inImage from './flagSvgs/in.svg';
import ioImage from './flagSvgs/io.svg';
import iqImage from './flagSvgs/iq.svg';
import irImage from './flagSvgs/ir.svg';
import isImage from './flagSvgs/is.svg';
import itImage from './flagSvgs/it.svg';
import jeImage from './flagSvgs/je.svg';
import jmImage from './flagSvgs/jm.svg';
import joImage from './flagSvgs/jo.svg';
import jpImage from './flagSvgs/jp.svg';
import keImage from './flagSvgs/ke.svg';
import kgImage from './flagSvgs/kg.svg';
import khImage from './flagSvgs/kh.svg';
import kiImage from './flagSvgs/ki.svg';
import kmImage from './flagSvgs/km.svg';
import knImage from './flagSvgs/kn.svg';
import kpImage from './flagSvgs/kp.svg';
import krImage from './flagSvgs/kr.svg';
import kwImage from './flagSvgs/kw.svg';
import kyImage from './flagSvgs/ky.svg';
import kzImage from './flagSvgs/kz.svg';
import laImage from './flagSvgs/la.svg';
import lbImage from './flagSvgs/lb.svg';
import lcImage from './flagSvgs/lc.svg';
import liImage from './flagSvgs/li.svg';
import lkImage from './flagSvgs/lk.svg';
import lrImage from './flagSvgs/lr.svg';
import lsImage from './flagSvgs/ls.svg';
import ltImage from './flagSvgs/lt.svg';
import luImage from './flagSvgs/lu.svg';
import lvImage from './flagSvgs/lv.svg';
import lyImage from './flagSvgs/ly.svg';
import maImage from './flagSvgs/ma.svg';
import mcImage from './flagSvgs/mc.svg';
import mdImage from './flagSvgs/md.svg';
import meImage from './flagSvgs/me.svg';
import mfImage from './flagSvgs/mf.svg';
import mgImage from './flagSvgs/mg.svg';
import mhImage from './flagSvgs/mh.svg';
import mkImage from './flagSvgs/mk.svg';
import mlImage from './flagSvgs/ml.svg';
import mmImage from './flagSvgs/mm.svg';
import mnImage from './flagSvgs/mn.svg';
import moImage from './flagSvgs/mo.svg';
import mpImage from './flagSvgs/mp.svg';
import mqImage from './flagSvgs/mq.svg';
import mrImage from './flagSvgs/mr.svg';
import msImage from './flagSvgs/ms.svg';
import mtImage from './flagSvgs/mt.svg';
import muImage from './flagSvgs/mu.svg';
import mvImage from './flagSvgs/mv.svg';
import mwImage from './flagSvgs/mw.svg';
import mxImage from './flagSvgs/mx.svg';
import myImage from './flagSvgs/my.svg';
import mzImage from './flagSvgs/mz.svg';
import naImage from './flagSvgs/na.svg';
import ncImage from './flagSvgs/nc.svg';
import neImage from './flagSvgs/ne.svg';
import nfImage from './flagSvgs/nf.svg';
import ngImage from './flagSvgs/ng.svg';
import niImage from './flagSvgs/ni.svg';
import nlImage from './flagSvgs/nl.svg';
import noImage from './flagSvgs/no.svg';
import npImage from './flagSvgs/np.svg';
import nrImage from './flagSvgs/nr.svg';
import nuImage from './flagSvgs/nu.svg';
import nzImage from './flagSvgs/nz.svg';
import omImage from './flagSvgs/om.svg';
import paImage from './flagSvgs/pa.svg';
import peImage from './flagSvgs/pe.svg';
import pfImage from './flagSvgs/pf.svg';
import pgImage from './flagSvgs/pg.svg';
import phImage from './flagSvgs/ph.svg';
import pkImage from './flagSvgs/pk.svg';
import plImage from './flagSvgs/pl.svg';
import pmImage from './flagSvgs/pm.svg';
import pnImage from './flagSvgs/pn.svg';
import prImage from './flagSvgs/pr.svg';
import psImage from './flagSvgs/ps.svg';
import ptImage from './flagSvgs/pt.svg';
import pwImage from './flagSvgs/pw.svg';
import pyImage from './flagSvgs/py.svg';
import qaImage from './flagSvgs/qa.svg';
import reImage from './flagSvgs/re.svg';
import roImage from './flagSvgs/ro.svg';
import rsImage from './flagSvgs/rs.svg';
import ruImage from './flagSvgs/ru.svg';
import rwImage from './flagSvgs/rw.svg';
import saImage from './flagSvgs/sa.svg';
import sbImage from './flagSvgs/sb.svg';
import scImage from './flagSvgs/sc.svg';
import sdImage from './flagSvgs/sd.svg';
import seImage from './flagSvgs/se.svg';
import sgImage from './flagSvgs/sg.svg';
import shImage from './flagSvgs/sh.svg';
import siImage from './flagSvgs/si.svg';
import skImage from './flagSvgs/sk.svg';
import slImage from './flagSvgs/sl.svg';
import smImage from './flagSvgs/sm.svg';
import snImage from './flagSvgs/sn.svg';
import soImage from './flagSvgs/so.svg';
import srImage from './flagSvgs/sr.svg';
import ssImage from './flagSvgs/ss.svg';
import stImage from './flagSvgs/st.svg';
import svImage from './flagSvgs/sv.svg';
import sxImage from './flagSvgs/sx.svg';
import syImage from './flagSvgs/sy.svg';
import szImage from './flagSvgs/sz.svg';
import tcImage from './flagSvgs/tc.svg';
import tdImage from './flagSvgs/td.svg';
import tfImage from './flagSvgs/tf.svg';
import tgImage from './flagSvgs/tg.svg';
import thImage from './flagSvgs/th.svg';
import tjImage from './flagSvgs/tj.svg';
import tkImage from './flagSvgs/tk.svg';
import tlImage from './flagSvgs/tl.svg';
import tmImage from './flagSvgs/tm.svg';
import tnImage from './flagSvgs/tn.svg';
import toImage from './flagSvgs/to.svg';
import trImage from './flagSvgs/tr.svg';
import ttImage from './flagSvgs/tt.svg';
import tvImage from './flagSvgs/tv.svg';
import twImage from './flagSvgs/tw.svg';
import tzImage from './flagSvgs/tz.svg';
import uaImage from './flagSvgs/ua.svg';
import ugImage from './flagSvgs/ug.svg';
import umImage from './flagSvgs/um.svg';
import usImage from './flagSvgs/us.svg';
import uyImage from './flagSvgs/uy.svg';
import uzImage from './flagSvgs/uz.svg';
import vaImage from './flagSvgs/va.svg';
import vcImage from './flagSvgs/vc.svg';
import veImage from './flagSvgs/ve.svg';
import vgImage from './flagSvgs/vg.svg';
import viImage from './flagSvgs/vi.svg';
import vnImage from './flagSvgs/vn.svg';
import vuImage from './flagSvgs/vu.svg';
import wfImage from './flagSvgs/wf.svg';
import wsImage from './flagSvgs/ws.svg';
import xkImage from './flagSvgs/xk.svg';
import yeImage from './flagSvgs/ye.svg';
import ytImage from './flagSvgs/yt.svg';
import zaImage from './flagSvgs/za.svg';
import zmImage from './flagSvgs/zm.svg';
import zwImage from './flagSvgs/zw.svg';
import { MediaData } from './App';

export let images:MediaData[] = [];

images.push({code: 'ad', level: 2, image: adImage, name: 'Andorra' });
images.push({code: 'ae', level: 1, image: aeImage, name: 'United Arab Emirates' });
images.push({code: 'af', level: 1, image: afImage, name: 'Afghanistan' });
images.push({code: 'ag', level: 1, image: agImage, name: 'Antigua and Barbuda' });
images.push({code: 'ai', level: 2, image: aiImage, name: 'Anguilla' });
images.push({code: 'al', level: 1, image: alImage, name: 'Albania' });
images.push({code: 'am', level: 1, image: amImage, name: 'Armenia' });
images.push({code: 'ao', level: 1, image: aoImage, name: 'Angola' });
images.push({code: 'aq', level: 2, image: aqImage, name: 'Antarctica' });
images.push({code: 'ar', level: 0, image: arImage, name: 'Argentina' });
images.push({code: 'as', level: 2, image: asImage, name: 'American Samoa' });
images.push({code: 'at', level: 0, image: atImage, name: 'Austria' });
images.push({code: 'au', level: 0, image: auImage, name: 'Australia' });
images.push({code: 'aw', level: 1, image: awImage, name: 'Aruba' });
images.push({code: 'ax', level: 2, image: axImage, name: 'Åland Islands' });
images.push({code: 'az', level: 1, image: azImage, name: 'Azerbaijan' });
images.push({code: 'ba', level: 1, image: baImage, name: 'Bosnia and Herzegovina' });
images.push({code: 'bb', level: 1, image: bbImage, name: 'Barbados' });
images.push({code: 'bd', level: 0, image: bdImage, name: 'Bangladesh' });
images.push({code: 'be', level: 0, image: beImage, name: 'Belgium' });
images.push({code: 'bf', level: 1, image: bfImage, name: 'Burkina Faso' });
images.push({code: 'bg', level: 0, image: bgImage, name: 'Bulgaria' });
images.push({code: 'bh', level: 1, image: bhImage, name: 'Bahrain' });
images.push({code: 'bi', level: 1, image: biImage, name: 'Burundi' });
images.push({code: 'bj', level: 1, image: bjImage, name: 'Benin' });
images.push({code: 'bl', level: 2, image: blImage, name: 'Saint Barthélemy' });
images.push({code: 'bm', level: 1, image: bmImage, name: 'Bermuda' });
images.push({code: 'bn', level: 1, image: bnImage, name: 'Brunei' });
images.push({code: 'bo', level: 1, image: boImage, name: 'Bolivia' });
images.push({code: 'bq', level: 2, image: bqImage, name: 'Caribbean Netherlands' });
images.push({code: 'br', level: 0, image: brImage, name: 'Brazil' });
images.push({code: 'bs', level: 1, image: bsImage, name: 'Bahamas' });
images.push({code: 'bt', level: 1, image: btImage, name: 'Bhutan' });
images.push({code: 'bw', level: 1, image: bwImage, name: 'Botswana' });
images.push({code: 'by', level: 1, image: byImage, name: 'Belarus' });
images.push({code: 'bz', level: 1, image: bzImage, name: 'Belize' });
images.push({code: 'ca', level: 0, image: caImage, name: 'Canada' });
images.push({code: 'cc', level: 2, image: ccImage, name: 'Cocos (Keeling) Islands' });
images.push({code: 'cd', level: 1, image: cdImage, name: 'DR Congo' });
images.push({code: 'cf', level: 1, image: cfImage, name: 'Central African Republic' });
images.push({code: 'cg', level: 1, image: cgImage, name: 'Republic of the Congo' });
images.push({code: 'ch', level: 0, image: chImage, name: 'Switzerland' });
images.push({code: 'ci', level: 1, image: ciImage, name: 'Côte d\'Ivoire (Ivory Coast)' });
images.push({code: 'ck', level: 2, image: ckImage, name: 'Cook Islands' });
images.push({code: 'cl', level: 1, image: clImage, name: 'Chile' });
images.push({code: 'cm', level: 1, image: cmImage, name: 'Cameroon' });
images.push({code: 'cn', level: 0, image: cnImage, name: 'China' });
images.push({code: 'co', level: 1, image: coImage, name: 'Colombia' });
images.push({code: 'cr', level: 1, image: crImage, name: 'Costa Rica' });
images.push({code: 'cu', level: 0, image: cuImage, name: 'Cuba' });
images.push({code: 'cv', level: 1, image: cvImage, name: 'Cape Verde' });
images.push({code: 'cw', level: 2, image: cwImage, name: 'Curaçao' });
images.push({code: 'cx', level: 2, image: cxImage, name: 'Christmas Island' });
images.push({code: 'cy', level: 0, image: cyImage, name: 'Cyprus' });
images.push({code: 'cz', level: 2, image: czImage, name: 'Czechia' });
images.push({code: 'de', level: 0, image: deImage, name: 'Germany' });
images.push({code: 'dj', level: 1, image: djImage, name: 'Djibouti' });
images.push({code: 'dk', level: 0, image: dkImage, name: 'Denmark' });
images.push({code: 'dm', level: 1, image: dmImage, name: 'Dominica' });
images.push({code: 'do', level: 1, image: doImage, name: 'Dominican Republic' });
images.push({code: 'dz', level: 0, image: dzImage, name: 'Algeria' });
images.push({code: 'ec', level: 1, image: ecImage, name: 'Ecuador' });
images.push({code: 'ee', level: 1, image: eeImage, name: 'Estonia' });
images.push({code: 'eg', level: 0, image: egImage, name: 'Egypt' });
images.push({code: 'eh', level: 2, image: ehImage, name: 'Western Sahara' });
images.push({code: 'er', level: 1, image: erImage, name: 'Eritrea' });
images.push({code: 'es', level: 0, image: esImage, name: 'Spain' });
images.push({code: 'et', level: 1, image: etImage, name: 'Ethiopia' });
images.push({code: 'fi', level: 0, image: fiImage, name: 'Finland' });
images.push({code: 'fj', level: 1, image: fjImage, name: 'Fiji' });
images.push({code: 'fk', level: 2, image: fkImage, name: 'Falkland Islands' });
images.push({code: 'fm', level: 1, image: fmImage, name: 'Micronesia' });
images.push({code: 'fo', level: 2, image: foImage, name: 'Faroe Islands' });
images.push({code: 'fr', level: 0, image: frImage, name: 'France' });
images.push({code: 'ga', level: 1, image: gaImage, name: 'Gabon' });
images.push({code: 'gb', level: 0, image: gbImage, name: 'United Kingdom' });
images.push({code: 'gbeng', level: 0, image: gbengImage, name: 'England' });
images.push({code: 'gbnir', level: 0, image: gbnirImage, name: 'Northern Ireland' });
images.push({code: 'gbsct', level: 0, image: gbsctImage, name: 'Scotland' });
images.push({code: 'gbwls', level: 0, image: gbwlsImage, name: 'Wales' });
images.push({code: 'gd', level: 1, image: gdImage, name: 'Grenada' });
images.push({code: 'ge', level: 1, image: geImage, name: 'Georgia' });
images.push({code: 'gf', level: 2, image: gfImage, name: 'French Guiana' });
images.push({code: 'gg', level: 2, image: ggImage, name: 'Guernsey' });
images.push({code: 'gh', level: 1, image: ghImage, name: 'Ghana' });
images.push({code: 'gi', level: 2, image: giImage, name: 'Gibraltar' });
images.push({code: 'gl', level: 2, image: glImage, name: 'Greenland' });
images.push({code: 'gm', level: 1, image: gmImage, name: 'Gambia' });
images.push({code: 'gn', level: 1, image: gnImage, name: 'Guinea' });
images.push({code: 'gp', level: 2, image: gpImage, name: 'Guadeloupe' });
images.push({code: 'gq', level: 1, image: gqImage, name: 'Equatorial Guinea' });
images.push({code: 'gr', level: 0, image: grImage, name: 'Greece' });
images.push({code: 'gs', level: 2, image: gsImage, name: 'South Georgia' });
images.push({code: 'gt', level: 1, image: gtImage, name: 'Guatemala' });
images.push({code: 'gu', level: 2, image: guImage, name: 'Guam' });
images.push({code: 'gw', level: 2, image: gwImage, name: 'Guinea-Bissau' });
images.push({code: 'gy', level: 1, image: gyImage, name: 'Guyana' });
images.push({code: 'hk', level: 0, image: hkImage, name: 'Hong Kong' });
images.push({code: 'hm', level: 2, image: hmImage, name: 'Heard Island and McDonald Islands' });
images.push({code: 'hn', level: 1, image: hnImage, name: 'Honduras' });
images.push({code: 'hr', level: 0, image: hrImage, name: 'Croatia' });
images.push({code: 'ht', level: 1, image: htImage, name: 'Haiti' });
images.push({code: 'hu', level: 1, image: huImage, name: 'Hungary' });
images.push({code: 'id', level: 1, image: idImage, name: 'Indonesia' });
images.push({code: 'ie', level: 0, image: ieImage, name: 'Ireland' });
images.push({code: 'il', level: 0, image: ilImage, name: 'Israel' });
images.push({code: 'im', level: 1, image: imImage, name: 'Isle of Man' });
images.push({code: 'in', level: 0, image: inImage, name: 'India' });
images.push({code: 'io', level: 2, image: ioImage, name: 'British Indian Ocean Territory' });
images.push({code: 'iq', level: 1, image: iqImage, name: 'Iraq' });
images.push({code: 'ir', level: 1, image: irImage, name: 'Iran' });
images.push({code: 'is', level: 1, image: isImage, name: 'Iceland' });
images.push({code: 'it', level: 0, image: itImage, name: 'Italy' });
images.push({code: 'je', level: 2, image: jeImage, name: 'Jersey' });
images.push({code: 'jm', level: 0, image: jmImage, name: 'Jamaica' });
images.push({code: 'jo', level: 1, image: joImage, name: 'Jordan' });
images.push({code: 'jp', level: 0, image: jpImage, name: 'Japan' });
images.push({code: 'ke', level: 1, image: keImage, name: 'Kenya' });
images.push({code: 'kg', level: 1, image: kgImage, name: 'Kyrgyzstan' });
images.push({code: 'kh', level: 1, image: khImage, name: 'Cambodia' });
images.push({code: 'ki', level: 1, image: kiImage, name: 'Kiribati' });
images.push({code: 'km', level: 1, image: kmImage, name: 'Comoros' });
images.push({code: 'kn', level: 1, image: knImage, name: 'Saint Kitts and Nevis' });
images.push({code: 'kp', level: 1, image: kpImage, name: 'North Korea' });
images.push({code: 'kr', level: 0, image: krImage, name: 'South Korea' });
images.push({code: 'kw', level: 1, image: kwImage, name: 'Kuwait' });
images.push({code: 'ky', level: 2, image: kyImage, name: 'Cayman Islands' });
images.push({code: 'kz', level: 1, image: kzImage, name: 'Kazakhstan' });
images.push({code: 'la', level: 1, image: laImage, name: 'Laos' });
images.push({code: 'lb', level: 1, image: lbImage, name: 'Lebanon' });
images.push({code: 'lc', level: 1, image: lcImage, name: 'Saint Lucia' });
images.push({code: 'li', level: 1, image: liImage, name: 'Liechtenstein' });
images.push({code: 'lk', level: 1, image: lkImage, name: 'Sri Lanka' });
images.push({code: 'lr', level: 1, image: lrImage, name: 'Liberia' });
images.push({code: 'ls', level: 1, image: lsImage, name: 'Lesotho' });
images.push({code: 'lt', level: 1, image: ltImage, name: 'Lithuania' });
images.push({code: 'lu', level: 1, image: luImage, name: 'Luxembourg' });
images.push({code: 'lv', level: 1, image: lvImage, name: 'Latvia' });
images.push({code: 'ly', level: 1, image: lyImage, name: 'Libya' });
images.push({code: 'ma', level: 1, image: maImage, name: 'Morocco' });
images.push({code: 'mc', level: 1, image: mcImage, name: 'Monaco' });
images.push({code: 'md', level: 1, image: mdImage, name: 'Moldova' });
images.push({code: 'me', level: 1, image: meImage, name: 'Montenegro' });
images.push({code: 'mf', level: 2, image: mfImage, name: 'Saint Martin' });
images.push({code: 'mg', level: 1, image: mgImage, name: 'Madagascar' });
images.push({code: 'mh', level: 1, image: mhImage, name: 'Marshall Islands' });
images.push({code: 'mk', level: 1, image: mkImage, name: 'North Macedonia' });
images.push({code: 'ml', level: 1, image: mlImage, name: 'Mali' });
images.push({code: 'mm', level: 2, image: mmImage, name: 'Myanmar' });
images.push({code: 'mn', level: 1, image: mnImage, name: 'Mongolia' });
images.push({code: 'mo', level: 2, image: moImage, name: 'Macau' });
images.push({code: 'mp', level: 2, image: mpImage, name: 'Northern Mariana Islands' });
images.push({code: 'mq', level: 2, image: mqImage, name: 'Martinique' });
images.push({code: 'mr', level: 1, image: mrImage, name: 'Mauritania' });
images.push({code: 'ms', level: 2, image: msImage, name: 'Montserrat' });
images.push({code: 'mt', level: 1, image: mtImage, name: 'Malta' });
images.push({code: 'mu', level: 1, image: muImage, name: 'Mauritius' });
images.push({code: 'mv', level: 1, image: mvImage, name: 'Maldives' });
images.push({code: 'mw', level: 1, image: mwImage, name: 'Malawi' });
images.push({code: 'mx', level: 0, image: mxImage, name: 'Mexico' });
images.push({code: 'my', level: 1, image: myImage, name: 'Malaysia' });
images.push({code: 'mz', level: 1, image: mzImage, name: 'Mozambique' });
images.push({code: 'na', level: 1, image: naImage, name: 'Namibia' });
images.push({code: 'nc', level: 2, image: ncImage, name: 'New Caledonia' });
images.push({code: 'ne', level: 1, image: neImage, name: 'Niger' });
images.push({code: 'nf', level: 2, image: nfImage, name: 'Norfolk Island' });
images.push({code: 'ng', level: 1, image: ngImage, name: 'Nigeria' });
images.push({code: 'ni', level: 1, image: niImage, name: 'Nicaragua' });
images.push({code: 'nl', level: 0, image: nlImage, name: 'Netherlands' });
images.push({code: 'no', level: 0, image: noImage, name: 'Norway' });
images.push({code: 'np', level: 1, image: npImage, name: 'Nepal' });
images.push({code: 'nr', level: 1, image: nrImage, name: 'Nauru' });
images.push({code: 'nu', level: 2, image: nuImage, name: 'Niue' });
images.push({code: 'nz', level: 0, image: nzImage, name: 'New Zealand' });
images.push({code: 'om', level: 1, image: omImage, name: 'Oman' });
images.push({code: 'pa', level: 1, image: paImage, name: 'Panama' });
images.push({code: 'pe', level: 1, image: peImage, name: 'Peru' });
images.push({code: 'pf', level: 2, image: pfImage, name: 'French Polynesia' });
images.push({code: 'pg', level: 1, image: pgImage, name: 'Papua New Guinea' });
images.push({code: 'ph', level: 1, image: phImage, name: 'Philippines' });
images.push({code: 'pk', level: 0, image: pkImage, name: 'Pakistan' });
images.push({code: 'pl', level: 0, image: plImage, name: 'Poland' });
images.push({code: 'pm', level: 2, image: pmImage, name: 'Saint Pierre and Miquelon' });
images.push({code: 'pn', level: 1, image: pnImage, name: 'Pitcairn Islands' });
images.push({code: 'pr', level: 2, image: prImage, name: 'Puerto Rico' });
images.push({code: 'ps', level: 2, image: psImage, name: 'Palestine' });
images.push({code: 'pt', level: 0, image: ptImage, name: 'Portugal' });
images.push({code: 'pw', level: 1, image: pwImage, name: 'Palau' });
images.push({code: 'py', level: 1, image: pyImage, name: 'Paraguay' });
images.push({code: 'qa', level: 1, image: qaImage, name: 'Qatar' });
images.push({code: 're', level: 2, image: reImage, name: 'Réunion' });
images.push({code: 'ro', level: 0, image: roImage, name: 'Romania' });
images.push({code: 'rs', level: 1, image: rsImage, name: 'Serbia' });
images.push({code: 'ru', level: 0, image: ruImage, name: 'Russia' });
images.push({code: 'rw', level: 1, image: rwImage, name: 'Rwanda' });
images.push({code: 'sa', level: 0, image: saImage, name: 'Saudi Arabia' });
images.push({code: 'sb', level: 1, image: sbImage, name: 'Solomon Islands' });
images.push({code: 'sc', level: 1, image: scImage, name: 'Seychelles' });
images.push({code: 'sd', level: 1, image: sdImage, name: 'Sudan' });
images.push({code: 'se', level: 0, image: seImage, name: 'Sweden' });
images.push({code: 'sg', level: 1, image: sgImage, name: 'Singapore' });
images.push({code: 'sh', level: 2, image: shImage, name: 'Saint Helena, Ascension and Tristan da Cunha' });
images.push({code: 'si', level: 0, image: siImage, name: 'Slovenia' });
images.push({code: 'sk', level: 0, image: skImage, name: 'Slovakia' });
images.push({code: 'sl', level: 1, image: slImage, name: 'Sierra Leone' });
images.push({code: 'sm', level: 1, image: smImage, name: 'San Marino' });
images.push({code: 'sn', level: 0, image: snImage, name: 'Senegal' });
images.push({code: 'so', level: 0, image: soImage, name: 'Somalia' });
images.push({code: 'sr', level: 1, image: srImage, name: 'Suriname' });
images.push({code: 'ss', level: 1, image: ssImage, name: 'South Sudan' });
images.push({code: 'st', level: 2, image: stImage, name: 'São Tomé and Príncipe' });
images.push({code: 'sv', level: 1, image: svImage, name: 'El Salvador' });
images.push({code: 'sx', level: 2, image: sxImage, name: 'Sint Maarten' });
images.push({code: 'sy', level: 0, image: syImage, name: 'Syria' });
images.push({code: 'sz', level: 2, image: szImage, name: 'Eswatini (Swaziland)' });
images.push({code: 'tc', level: 2, image: tcImage, name: 'Turks and Caicos Islands' });
images.push({code: 'td', level: 1, image: tdImage, name: 'Chad' });
images.push({code: 'tf', level: 2, image: tfImage, name: 'French Southern and Antarctic Lands' });
images.push({code: 'tg', level: 1, image: tgImage, name: 'Togo' });
images.push({code: 'th', level: 0, image: thImage, name: 'Thailand' });
images.push({code: 'tj', level: 1, image: tjImage, name: 'Tajikistan' });
images.push({code: 'tk', level: 2, image: tkImage, name: 'Tokelau' });
images.push({code: 'tl', level: 1, image: tlImage, name: 'Timor-Leste' });
images.push({code: 'tm', level: 1, image: tmImage, name: 'Turkmenistan' });
images.push({code: 'tn', level: 1, image: tnImage, name: 'Tunisia' });
images.push({code: 'to', level: 1, image: toImage, name: 'Tonga' });
images.push({code: 'tr', level: 0, image: trImage, name: 'Turkey' });
images.push({code: 'tt', level: 1, image: ttImage, name: 'Trinidad and Tobago' });
images.push({code: 'tv', level: 1, image: tvImage, name: 'Tuvalu' });
images.push({code: 'tw', level: 2, image: twImage, name: 'Taiwan' });
images.push({code: 'tz', level: 0, image: tzImage, name: 'Tanzania' });
images.push({code: 'ua', level: 1, image: uaImage, name: 'Ukraine' });
images.push({code: 'ug', level: 1, image: ugImage, name: 'Uganda' });
images.push({code: 'um', level: 2, image: umImage, name: 'United States Minor Outlying Islands' });
images.push({code: 'us', level: 0, image: usImage, name: 'United States' });
images.push({code: 'uy', level: 1, image: uyImage, name: 'Uruguay' });
images.push({code: 'uz', level: 1, image: uzImage, name: 'Uzbekistan' });
images.push({code: 'va', level: 2, image: vaImage, name: 'Vatican City (Holy See)' });
images.push({code: 'vc', level: 1, image: vcImage, name: 'Saint Vincent and the Grenadines' });
images.push({code: 've', level: 1, image: veImage, name: 'Venezuela' });
images.push({code: 'vg', level: 2, image: vgImage, name: 'British Virgin Islands' });
images.push({code: 'vi', level: 2, image: viImage, name: 'United States Virgin Islands' });
images.push({code: 'vn', level: 0, image: vnImage, name: 'Vietnam' });
images.push({code: 'vu', level: 1, image: vuImage, name: 'Vanuatu' });
images.push({code: 'wf', level: 2, image: wfImage, name: 'Wallis and Futuna' });
images.push({code: 'ws', level: 1, image: wsImage, name: 'Samoa' });
images.push({code: 'xk', level: 2, image: xkImage, name: 'Kosovo' });
images.push({code: 'ye', level: 1, image: yeImage, name: 'Yemen' });
images.push({code: 'yt', level: 2, image: ytImage, name: 'Mayotte' });
images.push({code: 'za', level: 0, image: zaImage, name: 'South Africa' });
images.push({code: 'zm', level: 0, image: zmImage, name: 'Zambia' });
images.push({code: 'zw', level: 0, image: zwImage, name: 'Zimbabwe' });

export function getFlagImages(level: number): MediaData[]{
  return images.filter((im)=>{
    return im.level <= level;
  })
}

// generate code for importing flags 
// from a json for country names and svgs
// and building the images array 
/*
const json = require('./codes.json');
console.log(`json = ${json}`);
const codes = Object.keys(json);
console.log(`codes = ${JSON.stringify(codes)}`);
let printMe = '';
codes.forEach((c)=>{
  printMe += `import ${c}Image from './flagSvgs/${c}.svg';\n`;
})
printMe += `let images = {};`;
codes.forEach((c)=>{
  printMe += `images.push({code: '${c}', image: ${c}Image, name: '${json[c]}' });\n`;
})
console.log(printMe);
*/