import adImage from './svgs/ad.svg';
import aeImage from './svgs/ae.svg';
import afImage from './svgs/af.svg';
import agImage from './svgs/ag.svg';
import aiImage from './svgs/ai.svg';
import alImage from './svgs/al.svg';
import amImage from './svgs/am.svg';
import aoImage from './svgs/ao.svg';
import aqImage from './svgs/aq.svg';
import arImage from './svgs/ar.svg';
import asImage from './svgs/as.svg';
import atImage from './svgs/at.svg';
import auImage from './svgs/au.svg';
import awImage from './svgs/aw.svg';
import axImage from './svgs/ax.svg';
import azImage from './svgs/az.svg';
import baImage from './svgs/ba.svg';
import bbImage from './svgs/bb.svg';
import bdImage from './svgs/bd.svg';
import beImage from './svgs/be.svg';
import bfImage from './svgs/bf.svg';
import bgImage from './svgs/bg.svg';
import bhImage from './svgs/bh.svg';
import biImage from './svgs/bi.svg';
import bjImage from './svgs/bj.svg';
import blImage from './svgs/bl.svg';
import bmImage from './svgs/bm.svg';
import bnImage from './svgs/bn.svg';
import boImage from './svgs/bo.svg';
import bqImage from './svgs/bq.svg';
import brImage from './svgs/br.svg';
import bsImage from './svgs/bs.svg';
import btImage from './svgs/bt.svg';
import bvImage from './svgs/bv.svg';
import bwImage from './svgs/bw.svg';
import byImage from './svgs/by.svg';
import bzImage from './svgs/bz.svg';
import caImage from './svgs/ca.svg';
import ccImage from './svgs/cc.svg';
import cdImage from './svgs/cd.svg';
import cfImage from './svgs/cf.svg';
import cgImage from './svgs/cg.svg';
import chImage from './svgs/ch.svg';
import ciImage from './svgs/ci.svg';
import ckImage from './svgs/ck.svg';
import clImage from './svgs/cl.svg';
import cmImage from './svgs/cm.svg';
import cnImage from './svgs/cn.svg';
import coImage from './svgs/co.svg';
import crImage from './svgs/cr.svg';
import cuImage from './svgs/cu.svg';
import cvImage from './svgs/cv.svg';
import cwImage from './svgs/cw.svg';
import cxImage from './svgs/cx.svg';
import cyImage from './svgs/cy.svg';
import czImage from './svgs/cz.svg';
import deImage from './svgs/de.svg';
import djImage from './svgs/dj.svg';
import dkImage from './svgs/dk.svg';
import dmImage from './svgs/dm.svg';
import doImage from './svgs/do.svg';
import dzImage from './svgs/dz.svg';
import ecImage from './svgs/ec.svg';
import eeImage from './svgs/ee.svg';
import egImage from './svgs/eg.svg';
import ehImage from './svgs/eh.svg';
import erImage from './svgs/er.svg';
import esImage from './svgs/es.svg';
import etImage from './svgs/et.svg';
import fiImage from './svgs/fi.svg';
import fjImage from './svgs/fj.svg';
import fkImage from './svgs/fk.svg';
import fmImage from './svgs/fm.svg';
import foImage from './svgs/fo.svg';
import frImage from './svgs/fr.svg';
import gaImage from './svgs/ga.svg';
import gbImage from './svgs/gb.svg';
import gbengImage from './svgs/gb-eng.svg';
import gbnirImage from './svgs/gb-nir.svg';
import gbsctImage from './svgs/gb-sct.svg';
import gbwlsImage from './svgs/gb-wls.svg';
import gdImage from './svgs/gd.svg';
import geImage from './svgs/ge.svg';
import gfImage from './svgs/gf.svg';
import ggImage from './svgs/gg.svg';
import ghImage from './svgs/gh.svg';
import giImage from './svgs/gi.svg';
import glImage from './svgs/gl.svg';
import gmImage from './svgs/gm.svg';
import gnImage from './svgs/gn.svg';
import gpImage from './svgs/gp.svg';
import gqImage from './svgs/gq.svg';
import grImage from './svgs/gr.svg';
import gsImage from './svgs/gs.svg';
import gtImage from './svgs/gt.svg';
import guImage from './svgs/gu.svg';
import gwImage from './svgs/gw.svg';
import gyImage from './svgs/gy.svg';
import hkImage from './svgs/hk.svg';
import hmImage from './svgs/hm.svg';
import hnImage from './svgs/hn.svg';
import hrImage from './svgs/hr.svg';
import htImage from './svgs/ht.svg';
import huImage from './svgs/hu.svg';
import idImage from './svgs/id.svg';
import ieImage from './svgs/ie.svg';
import ilImage from './svgs/il.svg';
import imImage from './svgs/im.svg';
import inImage from './svgs/in.svg';
import ioImage from './svgs/io.svg';
import iqImage from './svgs/iq.svg';
import irImage from './svgs/ir.svg';
import isImage from './svgs/is.svg';
import itImage from './svgs/it.svg';
import jeImage from './svgs/je.svg';
import jmImage from './svgs/jm.svg';
import joImage from './svgs/jo.svg';
import jpImage from './svgs/jp.svg';
import keImage from './svgs/ke.svg';
import kgImage from './svgs/kg.svg';
import khImage from './svgs/kh.svg';
import kiImage from './svgs/ki.svg';
import kmImage from './svgs/km.svg';
import knImage from './svgs/kn.svg';
import kpImage from './svgs/kp.svg';
import krImage from './svgs/kr.svg';
import kwImage from './svgs/kw.svg';
import kyImage from './svgs/ky.svg';
import kzImage from './svgs/kz.svg';
import laImage from './svgs/la.svg';
import lbImage from './svgs/lb.svg';
import lcImage from './svgs/lc.svg';
import liImage from './svgs/li.svg';
import lkImage from './svgs/lk.svg';
import lrImage from './svgs/lr.svg';
import lsImage from './svgs/ls.svg';
import ltImage from './svgs/lt.svg';
import luImage from './svgs/lu.svg';
import lvImage from './svgs/lv.svg';
import lyImage from './svgs/ly.svg';
import maImage from './svgs/ma.svg';
import mcImage from './svgs/mc.svg';
import mdImage from './svgs/md.svg';
import meImage from './svgs/me.svg';
import mfImage from './svgs/mf.svg';
import mgImage from './svgs/mg.svg';
import mhImage from './svgs/mh.svg';
import mkImage from './svgs/mk.svg';
import mlImage from './svgs/ml.svg';
import mmImage from './svgs/mm.svg';
import mnImage from './svgs/mn.svg';
import moImage from './svgs/mo.svg';
import mpImage from './svgs/mp.svg';
import mqImage from './svgs/mq.svg';
import mrImage from './svgs/mr.svg';
import msImage from './svgs/ms.svg';
import mtImage from './svgs/mt.svg';
import muImage from './svgs/mu.svg';
import mvImage from './svgs/mv.svg';
import mwImage from './svgs/mw.svg';
import mxImage from './svgs/mx.svg';
import myImage from './svgs/my.svg';
import mzImage from './svgs/mz.svg';
import naImage from './svgs/na.svg';
import ncImage from './svgs/nc.svg';
import neImage from './svgs/ne.svg';
import nfImage from './svgs/nf.svg';
import ngImage from './svgs/ng.svg';
import niImage from './svgs/ni.svg';
import nlImage from './svgs/nl.svg';
import noImage from './svgs/no.svg';
import npImage from './svgs/np.svg';
import nrImage from './svgs/nr.svg';
import nuImage from './svgs/nu.svg';
import nzImage from './svgs/nz.svg';
import omImage from './svgs/om.svg';
import paImage from './svgs/pa.svg';
import peImage from './svgs/pe.svg';
import pfImage from './svgs/pf.svg';
import pgImage from './svgs/pg.svg';
import phImage from './svgs/ph.svg';
import pkImage from './svgs/pk.svg';
import plImage from './svgs/pl.svg';
import pmImage from './svgs/pm.svg';
import pnImage from './svgs/pn.svg';
import prImage from './svgs/pr.svg';
import psImage from './svgs/ps.svg';
import ptImage from './svgs/pt.svg';
import pwImage from './svgs/pw.svg';
import pyImage from './svgs/py.svg';
import qaImage from './svgs/qa.svg';
import reImage from './svgs/re.svg';
import roImage from './svgs/ro.svg';
import rsImage from './svgs/rs.svg';
import ruImage from './svgs/ru.svg';
import rwImage from './svgs/rw.svg';
import saImage from './svgs/sa.svg';
import sbImage from './svgs/sb.svg';
import scImage from './svgs/sc.svg';
import sdImage from './svgs/sd.svg';
import seImage from './svgs/se.svg';
import sgImage from './svgs/sg.svg';
import shImage from './svgs/sh.svg';
import siImage from './svgs/si.svg';
import sjImage from './svgs/sj.svg';
import skImage from './svgs/sk.svg';
import slImage from './svgs/sl.svg';
import smImage from './svgs/sm.svg';
import snImage from './svgs/sn.svg';
import soImage from './svgs/so.svg';
import srImage from './svgs/sr.svg';
import ssImage from './svgs/ss.svg';
import stImage from './svgs/st.svg';
import svImage from './svgs/sv.svg';
import sxImage from './svgs/sx.svg';
import syImage from './svgs/sy.svg';
import szImage from './svgs/sz.svg';
import tcImage from './svgs/tc.svg';
import tdImage from './svgs/td.svg';
import tfImage from './svgs/tf.svg';
import tgImage from './svgs/tg.svg';
import thImage from './svgs/th.svg';
import tjImage from './svgs/tj.svg';
import tkImage from './svgs/tk.svg';
import tlImage from './svgs/tl.svg';
import tmImage from './svgs/tm.svg';
import tnImage from './svgs/tn.svg';
import toImage from './svgs/to.svg';
import trImage from './svgs/tr.svg';
import ttImage from './svgs/tt.svg';
import tvImage from './svgs/tv.svg';
import twImage from './svgs/tw.svg';
import tzImage from './svgs/tz.svg';
import uaImage from './svgs/ua.svg';
import ugImage from './svgs/ug.svg';
import umImage from './svgs/um.svg';
import usImage from './svgs/us.svg';
import uyImage from './svgs/uy.svg';
import uzImage from './svgs/uz.svg';
import vaImage from './svgs/va.svg';
import vcImage from './svgs/vc.svg';
import veImage from './svgs/ve.svg';
import vgImage from './svgs/vg.svg';
import viImage from './svgs/vi.svg';
import vnImage from './svgs/vn.svg';
import vuImage from './svgs/vu.svg';
import wfImage from './svgs/wf.svg';
import wsImage from './svgs/ws.svg';
import xkImage from './svgs/xk.svg';
import yeImage from './svgs/ye.svg';
import ytImage from './svgs/yt.svg';
import zaImage from './svgs/za.svg';
import zmImage from './svgs/zm.svg';
import zwImage from './svgs/zw.svg';

export let images:{
  code: string,
  level: number,
  image: any,
  name: string,
}[] = [];

images.push({code: 'ad', level: 2, image: adImage, name: 'Andorra' });
images.push({code: 'ae', level: 1, image: aeImage, name: 'United Arab Emirates' });
images.push({code: 'af', level: 1, image: afImage, name: 'Afghanistan' });
images.push({code: 'ag', level: 1, image: agImage, name: 'Antigua and Barbuda' });
images.push({code: 'ai', level: 2, image: aiImage, name: 'Anguilla' });
images.push({code: 'al', level: 1, image: alImage, name: 'Albania' });
images.push({code: 'am', level: 1, image: amImage, name: 'Armenia' });
images.push({code: 'ao', level: 1, image: aoImage, name: 'Angola' });
images.push({code: 'aq', level: 2, image: aqImage, name: 'Antarctica' });
images.push({code: 'ar', level: 0, image: arImage, name: 'Argentina' });
images.push({code: 'as', level: 2, image: asImage, name: 'American Samoa' });
images.push({code: 'at', level: 0, image: atImage, name: 'Austria' });
images.push({code: 'au', level: 0, image: auImage, name: 'Australia' });
images.push({code: 'aw', level: 1, image: awImage, name: 'Aruba' });
images.push({code: 'ax', level: 2, image: axImage, name: 'Åland Islands' });
images.push({code: 'az', level: 1, image: azImage, name: 'Azerbaijan' });
images.push({code: 'ba', level: 1, image: baImage, name: 'Bosnia and Herzegovina' });
images.push({code: 'bb', level: 1, image: bbImage, name: 'Barbados' });
images.push({code: 'bd', level: 0, image: bdImage, name: 'Bangladesh' });
images.push({code: 'be', level: 0, image: beImage, name: 'Belgium' });
images.push({code: 'bf', level: 1, image: bfImage, name: 'Burkina Faso' });
images.push({code: 'bg', level: 0, image: bgImage, name: 'Bulgaria' });
images.push({code: 'bh', level: 1, image: bhImage, name: 'Bahrain' });
images.push({code: 'bi', level: 1, image: biImage, name: 'Burundi' });
images.push({code: 'bj', level: 1, image: bjImage, name: 'Benin' });
images.push({code: 'bl', level: 2, image: blImage, name: 'Saint Barthélemy' });
images.push({code: 'bm', level: 1, image: bmImage, name: 'Bermuda' });
images.push({code: 'bn', level: 1, image: bnImage, name: 'Brunei' });
images.push({code: 'bo', level: 1, image: boImage, name: 'Bolivia' });
images.push({code: 'bq', level: 2, image: bqImage, name: 'Caribbean Netherlands' });
images.push({code: 'br', level: 0, image: brImage, name: 'Brazil' });
images.push({code: 'bs', level: 1, image: bsImage, name: 'Bahamas' });
images.push({code: 'bt', level: 1, image: btImage, name: 'Bhutan' });
images.push({code: 'bw', level: 1, image: bwImage, name: 'Botswana' });
images.push({code: 'by', level: 1, image: byImage, name: 'Belarus' });
images.push({code: 'bz', level: 1, image: bzImage, name: 'Belize' });
images.push({code: 'ca', level: 0, image: caImage, name: 'Canada' });
images.push({code: 'cc', level: 2, image: ccImage, name: 'Cocos (Keeling) Islands' });
images.push({code: 'cd', level: 1, image: cdImage, name: 'DR Congo' });
images.push({code: 'cf', level: 1, image: cfImage, name: 'Central African Republic' });
images.push({code: 'cg', level: 1, image: cgImage, name: 'Republic of the Congo' });
images.push({code: 'ch', level: 0, image: chImage, name: 'Switzerland' });
images.push({code: 'ci', level: 1, image: ciImage, name: 'Côte d\'Ivoire (Ivory Coast)' });
images.push({code: 'ck', level: 2, image: ckImage, name: 'Cook Islands' });
images.push({code: 'cl', level: 1, image: clImage, name: 'Chile' });
images.push({code: 'cm', level: 1, image: cmImage, name: 'Cameroon' });
images.push({code: 'cn', level: 0, image: cnImage, name: 'China' });
images.push({code: 'co', level: 1, image: coImage, name: 'Colombia' });
images.push({code: 'cr', level: 1, image: crImage, name: 'Costa Rica' });
images.push({code: 'cu', level: 0, image: cuImage, name: 'Cuba' });
images.push({code: 'cv', level: 1, image: cvImage, name: 'Cape Verde' });
images.push({code: 'cw', level: 2, image: cwImage, name: 'Curaçao' });
images.push({code: 'cx', level: 2, image: cxImage, name: 'Christmas Island' });
images.push({code: 'cy', level: 0, image: cyImage, name: 'Cyprus' });
images.push({code: 'cz', level: 2, image: czImage, name: 'Czechia' });
images.push({code: 'de', level: 0, image: deImage, name: 'Germany' });
images.push({code: 'dj', level: 1, image: djImage, name: 'Djibouti' });
images.push({code: 'dk', level: 0, image: dkImage, name: 'Denmark' });
images.push({code: 'dm', level: 1, image: dmImage, name: 'Dominica' });
images.push({code: 'do', level: 1, image: doImage, name: 'Dominican Republic' });
images.push({code: 'dz', level: 0, image: dzImage, name: 'Algeria' });
images.push({code: 'ec', level: 1, image: ecImage, name: 'Ecuador' });
images.push({code: 'ee', level: 1, image: eeImage, name: 'Estonia' });
images.push({code: 'eg', level: 0, image: egImage, name: 'Egypt' });
images.push({code: 'eh', level: 2, image: ehImage, name: 'Western Sahara' });
images.push({code: 'er', level: 1, image: erImage, name: 'Eritrea' });
images.push({code: 'es', level: 0, image: esImage, name: 'Spain' });
images.push({code: 'et', level: 1, image: etImage, name: 'Ethiopia' });
images.push({code: 'fi', level: 0, image: fiImage, name: 'Finland' });
images.push({code: 'fj', level: 1, image: fjImage, name: 'Fiji' });
images.push({code: 'fk', level: 2, image: fkImage, name: 'Falkland Islands' });
images.push({code: 'fm', level: 1, image: fmImage, name: 'Micronesia' });
images.push({code: 'fo', level: 2, image: foImage, name: 'Faroe Islands' });
images.push({code: 'fr', level: 0, image: frImage, name: 'France' });
images.push({code: 'ga', level: 1, image: gaImage, name: 'Gabon' });
images.push({code: 'gb', level: 0, image: gbImage, name: 'United Kingdom' });
images.push({code: 'gbeng', level: 0, image: gbengImage, name: 'England' });
images.push({code: 'gbnir', level: 0, image: gbnirImage, name: 'Northern Ireland' });
images.push({code: 'gbsct', level: 0, image: gbsctImage, name: 'Scotland' });
images.push({code: 'gbwls', level: 0, image: gbwlsImage, name: 'Wales' });
images.push({code: 'gd', level: 1, image: gdImage, name: 'Grenada' });
images.push({code: 'ge', level: 1, image: geImage, name: 'Georgia' });
images.push({code: 'gf', level: 2, image: gfImage, name: 'French Guiana' });
images.push({code: 'gg', level: 2, image: ggImage, name: 'Guernsey' });
images.push({code: 'gh', level: 1, image: ghImage, name: 'Ghana' });
images.push({code: 'gi', level: 2, image: giImage, name: 'Gibraltar' });
images.push({code: 'gl', level: 2, image: glImage, name: 'Greenland' });
images.push({code: 'gm', level: 1, image: gmImage, name: 'Gambia' });
images.push({code: 'gn', level: 1, image: gnImage, name: 'Guinea' });
images.push({code: 'gp', level: 2, image: gpImage, name: 'Guadeloupe' });
images.push({code: 'gq', level: 1, image: gqImage, name: 'Equatorial Guinea' });
images.push({code: 'gr', level: 0, image: grImage, name: 'Greece' });
images.push({code: 'gs', level: 2, image: gsImage, name: 'South Georgia' });
images.push({code: 'gt', level: 1, image: gtImage, name: 'Guatemala' });
images.push({code: 'gu', level: 2, image: guImage, name: 'Guam' });
images.push({code: 'gw', level: 2, image: gwImage, name: 'Guinea-Bissau' });
images.push({code: 'gy', level: 1, image: gyImage, name: 'Guyana' });
images.push({code: 'hk', level: 0, image: hkImage, name: 'Hong Kong' });
images.push({code: 'hm', level: 2, image: hmImage, name: 'Heard Island and McDonald Islands' });
images.push({code: 'hn', level: 1, image: hnImage, name: 'Honduras' });
images.push({code: 'hr', level: 0, image: hrImage, name: 'Croatia' });
images.push({code: 'ht', level: 1, image: htImage, name: 'Haiti' });
images.push({code: 'hu', level: 1, image: huImage, name: 'Hungary' });
images.push({code: 'id', level: 1, image: idImage, name: 'Indonesia' });
images.push({code: 'ie', level: 0, image: ieImage, name: 'Ireland' });
images.push({code: 'il', level: 0, image: ilImage, name: 'Israel' });
images.push({code: 'im', level: 1, image: imImage, name: 'Isle of Man' });
images.push({code: 'in', level: 0, image: inImage, name: 'India' });
images.push({code: 'io', level: 2, image: ioImage, name: 'British Indian Ocean Territory' });
images.push({code: 'iq', level: 1, image: iqImage, name: 'Iraq' });
images.push({code: 'ir', level: 1, image: irImage, name: 'Iran' });
images.push({code: 'is', level: 1, image: isImage, name: 'Iceland' });
images.push({code: 'it', level: 0, image: itImage, name: 'Italy' });
images.push({code: 'je', level: 2, image: jeImage, name: 'Jersey' });
images.push({code: 'jm', level: 0, image: jmImage, name: 'Jamaica' });
images.push({code: 'jo', level: 1, image: joImage, name: 'Jordan' });
images.push({code: 'jp', level: 0, image: jpImage, name: 'Japan' });
images.push({code: 'ke', level: 1, image: keImage, name: 'Kenya' });
images.push({code: 'kg', level: 1, image: kgImage, name: 'Kyrgyzstan' });
images.push({code: 'kh', level: 1, image: khImage, name: 'Cambodia' });
images.push({code: 'ki', level: 1, image: kiImage, name: 'Kiribati' });
images.push({code: 'km', level: 1, image: kmImage, name: 'Comoros' });
images.push({code: 'kn', level: 1, image: knImage, name: 'Saint Kitts and Nevis' });
images.push({code: 'kp', level: 1, image: kpImage, name: 'North Korea' });
images.push({code: 'kr', level: 0, image: krImage, name: 'South Korea' });
images.push({code: 'kw', level: 1, image: kwImage, name: 'Kuwait' });
images.push({code: 'ky', level: 2, image: kyImage, name: 'Cayman Islands' });
images.push({code: 'kz', level: 1, image: kzImage, name: 'Kazakhstan' });
images.push({code: 'la', level: 1, image: laImage, name: 'Laos' });
images.push({code: 'lb', level: 1, image: lbImage, name: 'Lebanon' });
images.push({code: 'lc', level: 1, image: lcImage, name: 'Saint Lucia' });
images.push({code: 'li', level: 1, image: liImage, name: 'Liechtenstein' });
images.push({code: 'lk', level: 1, image: lkImage, name: 'Sri Lanka' });
images.push({code: 'lr', level: 1, image: lrImage, name: 'Liberia' });
images.push({code: 'ls', level: 1, image: lsImage, name: 'Lesotho' });
images.push({code: 'lt', level: 1, image: ltImage, name: 'Lithuania' });
images.push({code: 'lu', level: 1, image: luImage, name: 'Luxembourg' });
images.push({code: 'lv', level: 1, image: lvImage, name: 'Latvia' });
images.push({code: 'ly', level: 1, image: lyImage, name: 'Libya' });
images.push({code: 'ma', level: 1, image: maImage, name: 'Morocco' });
images.push({code: 'mc', level: 1, image: mcImage, name: 'Monaco' });
images.push({code: 'md', level: 1, image: mdImage, name: 'Moldova' });
images.push({code: 'me', level: 1, image: meImage, name: 'Montenegro' });
images.push({code: 'mf', level: 2, image: mfImage, name: 'Saint Martin' });
images.push({code: 'mg', level: 1, image: mgImage, name: 'Madagascar' });
images.push({code: 'mh', level: 1, image: mhImage, name: 'Marshall Islands' });
images.push({code: 'mk', level: 1, image: mkImage, name: 'North Macedonia' });
images.push({code: 'ml', level: 1, image: mlImage, name: 'Mali' });
images.push({code: 'mm', level: 2, image: mmImage, name: 'Myanmar' });
images.push({code: 'mn', level: 1, image: mnImage, name: 'Mongolia' });
images.push({code: 'mo', level: 2, image: moImage, name: 'Macau' });
images.push({code: 'mp', level: 2, image: mpImage, name: 'Northern Mariana Islands' });
images.push({code: 'mq', level: 2, image: mqImage, name: 'Martinique' });
images.push({code: 'mr', level: 1, image: mrImage, name: 'Mauritania' });
images.push({code: 'ms', level: 2, image: msImage, name: 'Montserrat' });
images.push({code: 'mt', level: 1, image: mtImage, name: 'Malta' });
images.push({code: 'mu', level: 1, image: muImage, name: 'Mauritius' });
images.push({code: 'mv', level: 1, image: mvImage, name: 'Maldives' });
images.push({code: 'mw', level: 1, image: mwImage, name: 'Malawi' });
images.push({code: 'mx', level: 0, image: mxImage, name: 'Mexico' });
images.push({code: 'my', level: 1, image: myImage, name: 'Malaysia' });
images.push({code: 'mz', level: 1, image: mzImage, name: 'Mozambique' });
images.push({code: 'na', level: 1, image: naImage, name: 'Namibia' });
images.push({code: 'nc', level: 2, image: ncImage, name: 'New Caledonia' });
images.push({code: 'ne', level: 1, image: neImage, name: 'Niger' });
images.push({code: 'nf', level: 2, image: nfImage, name: 'Norfolk Island' });
images.push({code: 'ng', level: 1, image: ngImage, name: 'Nigeria' });
images.push({code: 'ni', level: 1, image: niImage, name: 'Nicaragua' });
images.push({code: 'nl', level: 0, image: nlImage, name: 'Netherlands' });
images.push({code: 'no', level: 0, image: noImage, name: 'Norway' });
images.push({code: 'np', level: 1, image: npImage, name: 'Nepal' });
images.push({code: 'nr', level: 1, image: nrImage, name: 'Nauru' });
images.push({code: 'nu', level: 2, image: nuImage, name: 'Niue' });
images.push({code: 'nz', level: 0, image: nzImage, name: 'New Zealand' });
images.push({code: 'om', level: 1, image: omImage, name: 'Oman' });
images.push({code: 'pa', level: 1, image: paImage, name: 'Panama' });
images.push({code: 'pe', level: 1, image: peImage, name: 'Peru' });
images.push({code: 'pf', level: 2, image: pfImage, name: 'French Polynesia' });
images.push({code: 'pg', level: 1, image: pgImage, name: 'Papua New Guinea' });
images.push({code: 'ph', level: 1, image: phImage, name: 'Philippines' });
images.push({code: 'pk', level: 0, image: pkImage, name: 'Pakistan' });
images.push({code: 'pl', level: 0, image: plImage, name: 'Poland' });
images.push({code: 'pm', level: 2, image: pmImage, name: 'Saint Pierre and Miquelon' });
images.push({code: 'pn', level: 1, image: pnImage, name: 'Pitcairn Islands' });
images.push({code: 'pr', level: 2, image: prImage, name: 'Puerto Rico' });
images.push({code: 'ps', level: 2, image: psImage, name: 'Palestine' });
images.push({code: 'pt', level: 0, image: ptImage, name: 'Portugal' });
images.push({code: 'pw', level: 1, image: pwImage, name: 'Palau' });
images.push({code: 'py', level: 1, image: pyImage, name: 'Paraguay' });
images.push({code: 'qa', level: 1, image: qaImage, name: 'Qatar' });
images.push({code: 're', level: 2, image: reImage, name: 'Réunion' });
images.push({code: 'ro', level: 0, image: roImage, name: 'Romania' });
images.push({code: 'rs', level: 1, image: rsImage, name: 'Serbia' });
images.push({code: 'ru', level: 0, image: ruImage, name: 'Russia' });
images.push({code: 'rw', level: 1, image: rwImage, name: 'Rwanda' });
images.push({code: 'sa', level: 0, image: saImage, name: 'Saudi Arabia' });
images.push({code: 'sb', level: 1, image: sbImage, name: 'Solomon Islands' });
images.push({code: 'sc', level: 1, image: scImage, name: 'Seychelles' });
images.push({code: 'sd', level: 1, image: sdImage, name: 'Sudan' });
images.push({code: 'se', level: 0, image: seImage, name: 'Sweden' });
images.push({code: 'sg', level: 1, image: sgImage, name: 'Singapore' });
images.push({code: 'sh', level: 2, image: shImage, name: 'Saint Helena, Ascension and Tristan da Cunha' });
images.push({code: 'si', level: 0, image: siImage, name: 'Slovenia' });
images.push({code: 'sk', level: 0, image: skImage, name: 'Slovakia' });
images.push({code: 'sl', level: 1, image: slImage, name: 'Sierra Leone' });
images.push({code: 'sm', level: 1, image: smImage, name: 'San Marino' });
images.push({code: 'sn', level: 0, image: snImage, name: 'Senegal' });
images.push({code: 'so', level: 0, image: soImage, name: 'Somalia' });
images.push({code: 'sr', level: 1, image: srImage, name: 'Suriname' });
images.push({code: 'ss', level: 1, image: ssImage, name: 'South Sudan' });
images.push({code: 'st', level: 2, image: stImage, name: 'São Tomé and Príncipe' });
images.push({code: 'sv', level: 1, image: svImage, name: 'El Salvador' });
images.push({code: 'sx', level: 2, image: sxImage, name: 'Sint Maarten' });
images.push({code: 'sy', level: 0, image: syImage, name: 'Syria' });
images.push({code: 'sz', level: 2, image: szImage, name: 'Eswatini (Swaziland)' });
images.push({code: 'tc', level: 2, image: tcImage, name: 'Turks and Caicos Islands' });
images.push({code: 'td', level: 1, image: tdImage, name: 'Chad' });
images.push({code: 'tf', level: 2, image: tfImage, name: 'French Southern and Antarctic Lands' });
images.push({code: 'tg', level: 1, image: tgImage, name: 'Togo' });
images.push({code: 'th', level: 0, image: thImage, name: 'Thailand' });
images.push({code: 'tj', level: 1, image: tjImage, name: 'Tajikistan' });
images.push({code: 'tk', level: 2, image: tkImage, name: 'Tokelau' });
images.push({code: 'tl', level: 1, image: tlImage, name: 'Timor-Leste' });
images.push({code: 'tm', level: 1, image: tmImage, name: 'Turkmenistan' });
images.push({code: 'tn', level: 1, image: tnImage, name: 'Tunisia' });
images.push({code: 'to', level: 1, image: toImage, name: 'Tonga' });
images.push({code: 'tr', level: 0, image: trImage, name: 'Turkey' });
images.push({code: 'tt', level: 1, image: ttImage, name: 'Trinidad and Tobago' });
images.push({code: 'tv', level: 1, image: tvImage, name: 'Tuvalu' });
images.push({code: 'tw', level: 2, image: twImage, name: 'Taiwan' });
images.push({code: 'tz', level: 0, image: tzImage, name: 'Tanzania' });
images.push({code: 'ua', level: 1, image: uaImage, name: 'Ukraine' });
images.push({code: 'ug', level: 1, image: ugImage, name: 'Uganda' });
images.push({code: 'um', level: 2, image: umImage, name: 'United States Minor Outlying Islands' });
images.push({code: 'us', level: 0, image: usImage, name: 'United States' });
images.push({code: 'uy', level: 1, image: uyImage, name: 'Uruguay' });
images.push({code: 'uz', level: 1, image: uzImage, name: 'Uzbekistan' });
images.push({code: 'va', level: 2, image: vaImage, name: 'Vatican City (Holy See)' });
images.push({code: 'vc', level: 1, image: vcImage, name: 'Saint Vincent and the Grenadines' });
images.push({code: 've', level: 1, image: veImage, name: 'Venezuela' });
images.push({code: 'vg', level: 2, image: vgImage, name: 'British Virgin Islands' });
images.push({code: 'vi', level: 2, image: viImage, name: 'United States Virgin Islands' });
images.push({code: 'vn', level: 0, image: vnImage, name: 'Vietnam' });
images.push({code: 'vu', level: 1, image: vuImage, name: 'Vanuatu' });
images.push({code: 'wf', level: 2, image: wfImage, name: 'Wallis and Futuna' });
images.push({code: 'ws', level: 1, image: wsImage, name: 'Samoa' });
images.push({code: 'xk', level: 2, image: xkImage, name: 'Kosovo' });
images.push({code: 'ye', level: 1, image: yeImage, name: 'Yemen' });
images.push({code: 'yt', level: 2, image: ytImage, name: 'Mayotte' });
images.push({code: 'za', level: 0, image: zaImage, name: 'South Africa' });
images.push({code: 'zm', level: 0, image: zmImage, name: 'Zambia' });
images.push({code: 'zw', level: 0, image: zwImage, name: 'Zimbabwe' });

export function getImages(level: number){
  return images.filter((im)=>{
    return im.level <= level;
  })
}

// generate code for importing flags 
// from a json for country names and svgs
// and building the images array 
/*
const json = require('./codes.json');
console.log(`json = ${json}`);
const codes = Object.keys(json);
console.log(`codes = ${JSON.stringify(codes)}`);
let printMe = '';
codes.forEach((c)=>{
  printMe += `import ${c}Image from './svgs/${c}.svg';\n`;
})
printMe += `let images = {};`;
codes.forEach((c)=>{
  printMe += `images.push({code: '${c}', image: ${c}Image, name: '${json[c]}' });\n`;
})
console.log(printMe);
*/