export interface VehicleAdvert{
  adID: string,
  dealerID: string,
  imageID: string,
  title: string,
  subtitle: string,
  description: string,
  miles: string,
  price: string,
  berth: string,
  transmission: string,
  year: string,
  engine: string,
  owners: string,
  beltedSeats: string,
  image: string,
  spec: string[],
  weblink: string,
  dateScraped: string,
  dateUploaded: string,
}

